on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs hourly

jobs:
  run-kpm:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.23
      BRANCH_NAME: ${{ github.ref_name }}
      CACHE_KEY: catalogs-${{ github.ref_name }}

      REPO: ghcr.io/${{ github.repository }}
      CATALOG_TAG: latest
      CATALOG_DIR: catalog
      OPERATORS_DIR: community-operators/operators


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: community-operators-pipeline

      - name: Checkout community-operators
        id: catalog-repo
        uses: actions/checkout@v4
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators
          fetch-depth: 0

      - name: Checkout kpm
        uses: actions/checkout@v4
        with:
          repository: joelanford/kpm
          path: kpm

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/*.sum"

      - name: Install KPM
        run: (cd kpm && make install)
          
      - name: Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CATALOG_DIR }}
          key: ${{ env.CACHE_KEY }}

      - if: steps.cache-restore.outputs.cache-hit == 'true'
        run: |
          echo "KPM_PACKAGES=CHANGED" >> $GITHUB_ENV
          echo "SINCE_COMMIT=$(cat $CATALOG_DIR/commit)" >> $GITHUB_ENV
          echo "/commit" >> ${{ env.CATALOG_DIR }}/.indexignore
          
      - if: steps.cache-restore.outputs.cache-hit != 'true'
        run: echo "KPM_PACKAGES=ALL" >> $GITHUB_ENV        

      - name: Run kpm build script
        run: ./community-operators-pipeline/kpm.sh

      - name: Push updated artifacts to registry
        if: github.event_name == 'push' || github.event_name == 'schedule'
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          kpm push kpms/*.bundle.kpm
          kpm push kpms/*.catalog.kpm

      - name: Write operators commit to catalog dir
        run: |
          echo "/commit" >> ${{ env.CATALOG_DIR }}/.indexignore
          echo ${{ steps.catalog-repo.outputs.commit }} > ${{ env.CATALOG_DIR }}/commit

      - name: Save catalog updates
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CATALOG_DIR }}
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
