on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-kpm:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: 1.23
      REGISTRY: ghcr.io
      REPO: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}
      CACHE_KEY: catalogs-${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: community-operators-pipeline

      - name: Checkout community-operators
        uses: actions/checkout@v4
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators
          fetch-depth: 0

      - name: Checkout kpm
        uses: actions/checkout@v4
        with:
          repository: joelanford/kpm
          path: kpm

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install KPM
        run: (cd kpm && make install)
          
      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ./catalog
          key: ${{ env.CACHE_KEY }}

      - if: steps.cache.outputs.cache-hit == 'true'
        run: echo "KPM_PACKAGES=CHANGED" >> $GITHUB_ENV
          
      - if: steps.cache.outputs.cache-hit != 'true'
        run: echo "KPM_PACKAGES=ALL" >> $GITHUB_ENV        

      - run: find .
      - run: export
